from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config


#!!! SELECT MODE!!
MODE = "DEVELOPMENT"

#CLOSE ALL POSITIONS
ABORT_ALL_POSITIONS = True

#Find Cointegrated Pairs
FIND_COINTEGRATED = False

#PLACE TRADES
PLACE_TRADES = True

MANAGE_EXITS = True
#RESOLUTION
#1DAY, 4HOURS, 1HOUR, 30MINS, 15MINS, 5MINS, 1MIN
RESOLUTION = "15MINS"

#STATS WINDOW
WINDOW = 21
#THRESHOLDS
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 2.0
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880


#THRESHOLDS CLOSING
CLOSE_AT_ZSCORE_CROSS = True
ETHERIUM_ADDRESS = "0xD380E210d5A936509474bfafD338a6fa1f39016f"


#KEYS - PRODUCTION
#MUST TO BE ON MAINNET on DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")


#KEYS - TEST
#MUST TO BE ON TESTNET on DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

#KEYS - EXPORT
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET



#HOST EXPORT
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

#HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/SZT9B89Bdn2gXPR_n2YcnzEH5HlKI0HX"
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/PNV-NjJrAcynQ_xB3MlwINyV-rp1CKnZ"

HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET
